package com.example.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Room @Entity representing a security or fraud alert generated by the fraud detection engine.
 *
 * @property id Unique auto-generated identifier for the fraud alert.
 * @property description Human-readable details regarding the suspicious activity or threat.
 * @property severityLevel Level of risk associated with this alert (e.g., "LOW", "MEDIUM", "HIGH", "CRITICAL").
 * @property timestamp Epoch timestamp (milliseconds) when the alert was triggered.
 */
@Entity(tableName = "fraud_alerts")
data class FraudAlert(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val description: String,
    val severityLevel: String,
    val timestamp: Long = System.currentTimeMillis()
)
